// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  State = 3,
  Command = 4,
  Transition = 5,
  Memory = 6,
  MemoryName = 7,
  DataHeader = 9,
  DataDeclaration = 10,
  END = 11,
  LogicHeader = 13,
  LogicDeclaration = 14
